---
#PostgreSQL section
- name: Install the PostgreSQL repository RPM
  dnf:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    state: present
- name: Disable the built-in PostgreSQL module
  command: dnf -qy module disable postgresql
- name: Install PostgreSQL
  dnf:
    name: postgresql17-server
    state: present
- name: Initialize the database
  command: "/usr/pgsql-17/bin/postgresql-17-setup initdb"
- name: Enable and start postgresql
  service:
    name: postgresql-17
    status: restarted
    enabled: true
- name: Install community.postgresql.postgresql_db requirements
  dnf:
    name:
      - python3-pip
      - python3-devel
      - postgresql-devel
      - python3-psycopg2
- name: Create netbox database
  community.postgresql.postgresql_db:
    name: netbox
    owner: netbox
- name: Create psql user netbox
  community.postgresql.postgresql_user:
    login_db: netbox
    name: netbox
    password: TODO

#---
#Redis section
- name: Install Redis
  dnf:
    name: redis-server

#---
#Netbox section
- name: Install required packages
  dnf:
    name:
      - python3
      - python3-pip
      - python3-venv
      - python3-dev
      - build-essential
      - libxml2-dev
      - libxslt1-dev
      - libffi-dev
      - libpq-dev
      - libssl-dev
      - zlib1g-dev
- name: Download and unpach netbox release archive
  unarchive:
    src: https://github.com/netbox-community/netbox/archive/refs/tags/v4.3.2.tar.gz
    dest: /opt
    remote_src: yes
- name: Create netbox symlink
  file:
    src: /opt/netbox-4.3.2/
    dest: /opt/netbox
    state: link
- name: Create netbox user
  user:
    name: netbox
    group: netbox
    system: true
- name: Change some netbox directories ownership
  file:
    path:
      - /opt/netbox/netbox/media/
      - /opt/netbox/netbox/reports/
      - /opt/netbox/netbox/scripts/
    recurse: yes
    owner: netbox
    group: netbox
#- name: Generate secret key
#  command: python3 /opt/netbox/netbox/generate_secret_key.py
#  register: secret_key
- name: Copy configuration.py template
  template:
    src: templates/configuration.py.j2
    dest: /opt/netbox/netbox/netbox/configuration.py
- name: Run the upgrade script
  command: /opt/netbox/upgrade.sh
# - name: Create a super user
#   command: /opt/netbox/venv/bin/activate && python3 /opt/netbox/netbox/manage.py createsuperuser