---
#PostgreSQL section
- name: Install the PostgreSQL repository RPM
  dnf:
    name: https://download.postgresql.org/pub/repos/yum/reporpms/EL-9-x86_64/pgdg-redhat-repo-latest.noarch.rpm
    disable_gpg_check: true
    state: present
- name: Disable the built-in PostgreSQL module
  command: dnf -qy module disable postgresql
- name: Install PostgreSQL
  dnf:
    name: postgresql17-server
    state: present
- name: Initialize the database
  command: "/usr/pgsql-17/bin/postgresql-17-setup initdb"
  ignore_errors: true
- name: Enable and start postgresql
  service:
    name: postgresql-17
    state: restarted
    enabled: true
- name: Enable crb repository (needed to install perl-IPC run for postgresql-devel)
  command: dnf config-manager --set-enabled crb
- name: Install community.postgresql.postgresql_db requirements
  dnf:
    name:
      - perl-IPC-Run
      - python3.12-pip
      - python3.12-devel
      - postgresql17-devel
      - python3.12-psycopg2
- name: Create psql user netbox
  community.postgresql.postgresql_user:
    name: netbox
    password: "{{ postgres_password }}"
  become: true
  become_user: postgres
- name: Create netbox database
  community.postgresql.postgresql_db:
    name: netbox
    owner: netbox
  become: true
  become_user: postgres

#---
#Redis section
- name: Install Redis
  dnf:
    name: redis
- name: Restart and enable Redis
  service:
    name: redis
    state: restarted
    enabled: true

#---
#Netbox section
- name: Install required packages
  dnf:
    name:
      - python3.12
      - python3.12-pip
      - python3.12-devel
      - gcc
      - gcc-c++
      - make
      - libxml2-devel
      - libxslt-devel
      - libffi-devel
      - libpq-devel
      - openssl-devel
      - zlib-devel
- name: Download and unpack netbox release archive
  unarchive:
    src: https://github.com/netbox-community/netbox/archive/refs/tags/v4.3.2.tar.gz
    dest: /opt
    remote_src: yes
- name: Create netbox symlink
  file:
    src: /opt/netbox-4.3.2/
    dest: /opt/netbox
    state: link
- name: Create netbox group
  group:
    name: netbox
    state: present
    system: true
- name: Create netbox user
  user:
    name: netbox
    group: netbox
    system: true
- name: Change some netbox directories ownership
  file:
    path:
      - /opt/netbox/netbox/media/
      - /opt/netbox/netbox/reports/
      - /opt/netbox/netbox/scripts/
    recurse: yes
    owner: netbox
    group: netbox
#- name: Generate secret key
#  command: python3 /opt/netbox/netbox/generate_secret_key.py
#  register: secret_key
- name: Copy configuration.py template
  template:
    src: templates/configuration.py.j2
    dest: /opt/netbox/netbox/netbox/configuration.py
- name: Run the upgrade script
  command: PYTHON=/usr/bin/python3.12 /opt/netbox/upgrade.sh
# - name: Create a super user
#   command: /opt/netbox/venv/bin/activate && python3 /opt/netbox/netbox/manage.py createsuperuser